---
title: "Brosseau_NF"
author: "Maksym"
date: "3/7/2023"
output: html_document
---

```{r}
library(data.table)
library(tidyverse)
```


```{r}
nf1 = fread("/Users/plezar/Downloads/GSE163028_RAW/GSM4970432_cNF1_normalized_count_matrix.csv", sep=",")
nf1 = as.data.frame(nf1)
rownames(nf1) = nf1$V1
nf1$V1 = NULL

nf2 = fread("/Users/plezar/Downloads/GSE163028_RAW/GSM4970433_cNF2_normalized_count_matrix.csv", sep=",")
nf2 = as.data.frame(nf2)
rownames(nf2) = nf2$V1
nf2$V1 = NULL

nf3 = fread("/Users/plezar/Downloads/GSE163028_RAW/GSM4970434_cNF3_normalized_count_matrix.csv", sep=",")
nf3 = as.data.frame(nf3)
rownames(nf3) = nf3$V1
nf3$V1 = NULL

count_mtx = cbind(nf1, nf2, nf3)
metadata = data.frame(Sample = c(rep("NF1", ncol(nf1)), rep("NF2", ncol(nf2)), rep("NF3", ncol(nf3))))
rownames(metadata) = c(colnames(nf1), colnames(nf2), colnames(nf3))
```

```{r}
library(SeuratObject)

seurat_obj = CreateSeuratObject(
  counts = count_mtx,
  assay = "RNA",
  meta.data = metadata
)
```


## Clustering

```{r}
library(Seurat)
```


```{r}
seurat_obj <- FindVariableFeatures(seurat_obj, selection.method = "vst", nfeatures = 2000)
seurat_obj <- ScaleData(seurat_obj)
seurat_obj <- RunPCA(seurat_obj, features = VariableFeatures(object = seurat_obj))
ElbowPlot(seurat_obj)
```


```{r}
seurat_obj <- FindNeighbors(seurat_obj, dims = 1:12)
seurat_obj <- FindClusters(seurat_obj, resolution = 0.5)
seurat_obj <- RunUMAP(seurat_obj, dims = 1:12)
DimPlot(seurat_obj, label=T)
```

```{r}
DotPlot(
  seurat_obj,
  features = c("PTPRC", "ACTA2", "S100B", "HLA-DQA1", "PECAM1", "COL1A1", "CD163", "HLA-DRB1")
)
```

```{r}
Idents(seurat_obj) <- "RNA_snn_res.0.5"
seurat_obj <- RenameIdents(object = seurat_obj, 
                              "0" = "Fibroblast",
                              "1" = "Fibroblast",
                              "2" = "EC",
                              "3" = "Fibroblast",
                              "4" = "EC",
                              "5" = "Fibroblast",
                              "6" = "APC",
                              "7" = "PC",
                              "8" = "Schwann cell",
                           "9" = "Hematopoieic cell",
                           "10" = "n.d.",
                           "11" = "n.d.")
seurat_obj$cell.type = Idents(seurat_obj)
Idents(seurat_obj) = "cell.type"
DimPlot(seurat_obj)
```

```{r}
seurat_obj = subset(seurat_obj, idents = "n.d.", invert = T)
DimPlot(seurat_obj)
```

```{r}
p = DimPlot(seurat_obj, label = T,  label.size = 7, pt.size = .1, cols = c('#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf')) + NoLegend()
p
```

```{r}
ggsave(p, path="/Volumes/TOSHIBA/TIMElab/GSE163028_RAW", filename= "UMAP.pdf", width=5.1, height=5, dpi=700)
```




```{r}
saveRDS(seurat_obj, "/Volumes/TOSHIBA/TIMElab/GSE163028_RAW/seurat_obj.rds")
```

```{r}
library(Seurat)
seurat_obj = readRDS("/Volumes/TOSHIBA/TIMElab/GSE163028_RAW/seurat_obj.rds")
```


## Pseudobulk samples

```{r}
library(scuttle)
library(edgeR)

DefaultAssay(seurat_obj) <- "RNA"

merged_sce <- as.SingleCellExperiment(DietSeurat(seurat_obj))
merged_sce@assays@data$logcounts <- NULL
summed <- aggregateAcrossCells(merged_sce, 
                               id=colData(merged_sce)[,c("Sample")],
                               use.assay.type = 1)
y <- DGEList(counts(summed), samples=colData(summed))

discarded <- summed$ncells < 10
y <- y[,!discarded]

keep <- filterByExpr(y)
y <- y[keep,]
y <- calcNormFactors(y)
plotMDS(cpm(y, log=TRUE))
y$log2cpm = cpm(y, log=TRUE)
```



### ECM subtyping

```{r}
sigs = readRDS("/Volumes/TOSHIBA/TIMElab/bulk_RNAseq/ECM_gene_signatures.rds")
```

```{r}
library(scrabble)
library(ComplexHeatmap)
library(tidyverse)

sigs$ECMhi = sigs$ECMhi[sigs$ECMhi%in%rownames(y)]
sigs$ECMlo = sigs$ECMlo[sigs$ECMlo%in%rownames(y)]

sig_scores = scrabble::score(
  mat = y$log2cpm,
  groups = sigs
)

y$samples$ECMhi.score = sig_scores[,"ECMhi"]
y$samples$ECMlo.score = sig_scores[,"ECMlo"]

score_threshold = 0

y$samples$ECM.cluster = sig_scores %>%
  as.data.frame() %>%
  mutate(ECM.cluster = if_else(ECMhi > score_threshold & ECMlo < -(score_threshold), "ECMhi",
                               if_else(ECMhi < (-score_threshold) & ECMlo > score_threshold, "ECMlo", "undefined"))) %>%
  pull(ECM.cluster)
```

```{r}
library(circlize)

hcl = hclust(dist(sig_scores, method = "maximum"), method = "average")

ht = Heatmap(t(sig_scores),
        name = "Signature score",
        column_split = factor(y$samples$ECM.cluster),
        show_column_dend = F,
        show_row_dend = F,
        show_column_names = F,
        col = colorRamp2(seq(-.5, .5, length.out=11), colorRampPalette(c("#4DBBD5FF", "#E64B35FF"))(11)),
        width = unit(11, "cm"), 
        height = unit(.75, "cm"))

ht
```
## Matrisome expression

```{r}
matrisome_d = readxl::read_xlsx("/Volumes/TOSHIBA/TIMElab/bulk_RNAseq/matrisome_hs_masterlist.xlsx")
core_matrisome_d = matrisome_d %>% filter(Division=="Core matrisome")
core_matrisome_d = core_matrisome_d[core_matrisome_d$`Gene Symbol`%in%rownames(seurat_obj),]
```

Courtesy of raveancic
```{r}
PrctCellExpringGene <- function(object, genes, group.by = "all"){
    if(group.by == "all"){
        prct = unlist(lapply(genes,calc_helper, object=object))
        result = data.frame(Markers = genes, Cell_proportion = prct)
        return(result)
    }

    else{        
        list = SplitObject(object, group.by)
        factors = names(list)

        results = lapply(list, PrctCellExpringGene, genes=genes)
        for(i in 1:length(factors)){
        results[[i]]$Feature = factors[i]
        }
        combined = do.call("rbind", results)
        return(combined)
    }
}

calc_helper <- function(object,genes){
    counts = object[['RNA']]@counts
    ncells = ncol(counts)
    if(genes %in% row.names(counts)){
    sum(counts[genes,]>0)/ncells
    }else{return(NA)}
}
```

```{r}
prct_expressed = PrctCellExpringGene(seurat_obj, core_matrisome_d$`Gene Symbol`, group.by = "cell.type")
rownames(prct_expressed) = 1:nrow(prct_expressed)
```


```{r}
highly_expressed = unique(prct_expressed$Markers[prct_expressed$Cell_proportion>.1])
```


```{r}
p = DotPlot(
  seurat_obj, cluster.idents = T,
  scale = F,
  features = core_matrisome_d[core_matrisome_d$`Gene Symbol`%in%highly_expressed,]$`Gene Symbol`
) + coord_flip() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_colour_gradient2(low = "#3C5488FF", mid = "grey", high = "#DC0000FF")
p
```

```{r}
fig_path = "/Volumes/TOSHIBA/TIMElab/figures/FIG1/Brosseau_NF"
ggsave(p, path=fig_path, filename= "matrisome_expression.pdf", width=5, height=20, dpi = 700)
```



## Subclustering stromal cells

```{r}
seurat_obj_sub = subset(seurat_obj, idents = c("Fibroblast", "EC", "PC"))
```

```{r}
seurat_obj_sub = DietSeurat(seurat_obj_sub)
```

```{r}
seurat_obj_sub <- NormalizeData(seurat_obj_sub)
seurat_obj_sub <- FindVariableFeatures(seurat_obj_sub, selection.method = "vst", nfeatures = 2000)
seurat_obj_sub <- ScaleData(seurat_obj_sub)
seurat_obj_sub <- RunPCA(seurat_obj_sub, features = VariableFeatures(object = seurat_obj_sub))
ElbowPlot(seurat_obj_sub)
```


```{r}
seurat_obj_sub <- FindNeighbors(seurat_obj_sub, dims = 1:9)
seurat_obj_sub <- FindClusters(seurat_obj_sub, resolution = 0.5)
seurat_obj_sub <- RunUMAP(seurat_obj_sub, dims = 1:9)
Idents(seurat_obj_sub) <- "cell.type"
DimPlot(seurat_obj_sub)
```

```{r}
saveRDS(seurat_obj_sub, "/Volumes/TOSHIBA/TIMElab/GSE163028_RAW/stromal_cells.rds")
```



## SCIPAC

```{r}
load("/Volumes/TOSHIBA/TIMElab/GSE163028_RAW/SCIPAC_data.RData")
seurat_obj = readRDS("/Volumes/TOSHIBA/TIMElab/GSE163028_RAW/seurat_obj.rds")
```

```{r}
library(SCIPAC)
SCIPAC.res <- SCIPAC(bulk.dat = bulk.dat.dim.redu, y = y,
                     nfold = 21,
                     family = "binomial", ct.res = ct.res, 
                     ela.net.alpha = 0.4, bt.size = 50, 
                     numCores = 7, CI.alpha = 0.05)

SCIPAC.res
```


```{r}
seurat_obj@meta.data = seurat_obj@meta.data %>%
  rownames_to_column("cell_id") %>%
  left_join(
    SCIPAC.res %>% rownames_to_column("cell_id") %>% select(cell_id, Lambda.est,  Lambda.upper, Lambda.lower, sig, log.pval)
  ) %>%
  column_to_rownames("cell_id")
```


```{r}
p = DimPlot(seurat_obj,
        group.by = "sig",
        cols = c("#E64B35FF", "#4DBBD5FF", "#ededed")) + NoLegend()
p
```

```{r}
ggsave(p, path="/Volumes/TOSHIBA/TIMElab/GSE163028_RAW", filename= "NF_SCIPAC.pdf", width=5.1, height=5.1, dpi=700)
```


```{r}
p = DimPlot(seurat_obj, label = T,  label.size = 7, pt.size = .1, cols = c('#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf')) + NoLegend()
p
```

```{r}
ggsave(p, path="/Volumes/TOSHIBA/TIMElab/GSE163028_RAW", filename= "NF_UMAP.pdf", width=5.1, height=5, dpi=700)
```